[package]
name = "user-service"
version = "0.1.0"
authors = ["Soockee <gamingsockee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive"]}
tokio = { version = "1.5.0", features = ["full"] }
serde_json = "1.0.64"
warp = "0.3.1"
