# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: mongo
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: rootroot
      #MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - microservices
  app:
    image: master.ms.depressive.life/userservice:master
    ports: 
      - 13331:13331
    environment: 
      - AUTH_SERVICE_URL=http://zuul:8765/auth-app/api/v1/login
    labels:
      - "pt.fabiopina.mma.registry.eureka=true"
    networks:
      - microservices
    depends_on: 
      - db
networks:
  microservices:
    external:
      name: microservices